version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:18.12.1
    steps:
    - checkout
    - restore_cache:
        key: npm-v1-{{ checksum "package-lock.json" }}--{{ arch }}

    - restore_cache:
        key: node-v1-{{ checksum "package.json" }}--{{ arch }}

    - run: npm ci

    - save_cache:
        key: npm-v1-{{ checksum "package-lock.json" }}--{{ arch }}
        paths:
          - "package-lock.json"

    - save_cache:
        key: node-v1-{{ checksum "package.json" }}--{{ arch }}
        paths:
          - node_modules

    - run: npm run lint

  test:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}--{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}

      - run: npm ci

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}--{{ arch }}
          paths:
            - "package-lock.json"

      - save_cache:
          key: npm-v1-{{ checksum "package.json" }}--{{ arch }}
          paths:
            - node_modules

      - run:
          name: Jest Tests
          command: npm run test

workflows:
  lint-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
